---
# Source: juicefs-csi-driver/templates/mutatingwebhook.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: juicefs-cert
  namespace: kube-system
spec:
  duration: 43800h #5year
  dnsNames:
    - juicefs-admission-webhook
    - juicefs-admission-webhook.kube-system
    - juicefs-admission-webhook.kube-system.svc
  issuerRef:
    name: juicefs-selfsigned
    kind: Issuer
  secretName: juicefs-webhook-certs
---
# Source: juicefs-csi-driver/templates/mutatingwebhook.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: juicefs-selfsigned
  namespace: kube-system
spec:
  selfSigned: {}
---
# Source: juicefs-csi-driver/templates/mutatingwebhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: juicefs-admission-webhook
  annotations:
    cert-manager.io/inject-ca-from: "kube-system/juicefs-cert"
webhooks:
  - name: sidecar.inject.juicefs.com
    rules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE"]
        resources:   ["pods"]
    clientConfig:
      service:
        namespace: "kube-system"
        name: juicefs-admission-webhook
        path: "/juicefs/inject-v1-pod"
      caBundle: Cg==
    timeoutSeconds: 5
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1","v1beta1"]
    namespaceSelector:
      matchLabels:
        juicefs.com/enable-injection: "true"
