---
# Source: juicefs-csi-driver/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: juicefs-csi-controller-sa
  namespace:  "kube-system"
  labels:
    helm.sh/chart: juicefs-csi-driver-0.19.4
    app.kubernetes.io/name: juicefs-csi-driver
    app.kubernetes.io/instance: juicefs1
    app.kubernetes.io/version: "0.23.1"
    app.kubernetes.io/managed-by: Helm
---
# Source: juicefs-csi-driver/templates/serviceaccount.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: juicefs-csi-dashboard-sa
  namespace: "kube-system"
  labels:
    helm.sh/chart: juicefs-csi-driver-0.19.4
    app.kubernetes.io/name: juicefs-csi-driver
    app.kubernetes.io/instance: juicefs1
    app.kubernetes.io/version: "0.23.1"
    app.kubernetes.io/managed-by: Helm
---
# Source: juicefs-csi-driver/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: juicefs-csi-external-provisioner-role
  labels:
    helm.sh/chart: juicefs-csi-driver-0.19.4
    app.kubernetes.io/name: juicefs-csi-driver
    app.kubernetes.io/instance: juicefs1
    app.kubernetes.io/version: "0.23.1"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - persistentvolumeclaims/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - storage.k8s.io
  resources:
  - csinodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - create
  - update
  - patch
  - delete
  - list
  - watch
- apiGroups:
    - ""
  resources:
    - endpoints
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
- apiGroups:
    - apps
  resources:
    - daemonsets
  verbs:
    - get
    - list
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs:
    - get
    - watch
    - list
    - delete
    - update
    - create
- apiGroups:
    - ""
  resources:
    - configmaps
  verbs:
    - get
    - watch
    - list
    - delete
    - update
    - create
- apiGroups:
    - ""
  resources:
    - pods/exec
  verbs:
    - '*'
---
# Source: juicefs-csi-driver/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    helm.sh/chart: juicefs-csi-driver-0.19.4
    app.kubernetes.io/name: juicefs-csi-driver
    app.kubernetes.io/instance: juicefs1
    app.kubernetes.io/version: "0.23.1"
    app.kubernetes.io/managed-by: Helm
  name: juicefs-csi-dashboard-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - persistentvolumes
  - persistentvolumeclaims
  - persistentvolumeclaims/status
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/proxy
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
---
# Source: juicefs-csi-driver/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    helm.sh/chart: juicefs-csi-driver-0.19.4
    app.kubernetes.io/name: juicefs-csi-driver
    app.kubernetes.io/instance: juicefs1
    app.kubernetes.io/version: "0.23.1"
    app.kubernetes.io/managed-by: Helm
  name: juicefs-csi-provisioner-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: juicefs-csi-external-provisioner-role
subjects:
- kind: ServiceAccount
  name: juicefs-csi-controller-sa
  namespace: "kube-system"
---
# Source: juicefs-csi-driver/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    helm.sh/chart: juicefs-csi-driver-0.19.4
    app.kubernetes.io/name: juicefs-csi-driver
    app.kubernetes.io/instance: juicefs1
    app.kubernetes.io/version: "0.23.1"
    app.kubernetes.io/managed-by: Helm
  name: juicefs-csi-dashboard-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: juicefs-csi-dashboard-role
subjects:
- kind: ServiceAccount
  name: juicefs-csi-dashboard-sa
  namespace: "kube-system"
