apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-juice-step1
  name: my-juice-step1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-juice-step1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-juice-step1
    spec:
      containers:
      - image: nginx
        name: nginx
        command:
        - sh
        - "-c"
        - "while true; do date >> /datadir/1.txt; sleep 1; done "
        volumeMounts:
        - mountPath: /datadir
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: ce-static
