apiVersion: v1
stringData:
  name: minio
  bucket: http://192.168.255.246:30377/minio/test1
  metaurl: redis://192.168.255.246:30379
  storage: minio
  access-key: izBVVKTHxMZ91vLSmjI0
  secret-key: Tgugz3lxz8JVR9MazyDzjnSCcRdAlndp6pfhaBAo
kind: Secret
metadata:
  name: test1info
  namespace: kube-system
type: Opaque

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ce-static
  labels:
    juicefs-name: ce-static
spec:
  capacity:
    storage: 10Pi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  csi:
    driver: csi.juicefs.com
    volumeHandle: ce-static-handle
    fsType: juicefs
    nodePublishSecretRef:
      name: test1info
      namespace: kube-system
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ce-static
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: ""
  resources:
    requests:
      storage: 10Pi
  selector:
    matchLabels:
      juicefs-name: ce-static
---
