apiVersion: v1
stringData:
  name: minio
  bucket: http://minio.default:9000/minio/test
  metaurl: redis://svc-redis.default
  storage: minio
  access-key: nWfva9PJ1pH1a9mbsvid
  secret-key: wQGAg9QhJUhk7lglcnrlM45L7nrE6kAxC8cFLQZi
kind: Secret
metadata:
  name: test
  namespace: kube-system
type: Opaque

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ce-static
  labels:
    juicefs-name: ce-static
spec:
  capacity:
    storage: 10Pi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  csi:
    driver: csi.juicefs.com
    volumeHandle: ce-static-handle
    fsType: juicefs
    nodePublishSecretRef:
      name: test
      namespace: kube-system
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ce-static
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: ""
  resources:
    requests:
      storage: 10Pi
  selector:
    matchLabels:
      juicefs-name: ce-static
---
